server:
  port: 8031
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 47.99.179.219:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
    loadbalancer:
      ribbon:
        enabled: false