server:
  port: 8040
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 124.223.12.25:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
#springboot默认的日志级别是info级别，feign的debug级别的日志就不会输出
logging:
  level:
    com.timor.feign: debug
#feign日志局部配置
feign:
  client:
    config:
      product-service:
        loggerLevel: BASIC
#        contract: feign.Contract.Default  #设置为默认的契约
        # 连接超时时间 默认2s
        connectTimeout: 5000
        # 请求处理超时时间 默认5s
        readTimeout: 3000
        requestInterceptors[0]:
          com.timor.intercepter.feign.CustomFeignInterceptor